baseURL = "https://www.ursulahneumann.com"
languageCode = "en-us"
title = "Ursula Neumann's Blog"
theme = "mediumish"
summaryLength = 25
copyright = "Ursula Neumann - All rights reserved"
enableEmoji = true
publishDir = "public"
disqusShortname = "https-www-ursulahneumann-com"
#googleAnalytics = "UA-1XXXXXXX1-1"

[params]
  logo = "/images/logo.png"
  description =""
  #mailchimp = "you can provide a mailchimp-link here"

[params.author]
  name = "Ursula Neumann"
  thumbnail = "/images/headshot.jpg"
  description = "Creator of this blog."

[params.index]
  picture = "/images/headshot.jpg"
  title = "Ursula Neumann PhD"
  subtitle = ""
  mdtext = '''
Hi and welcome! I received my PhD in Cell and Developmental Biology at the University of \
British Columbia researching diabetes.  Currently I work as a Senior Scientist @ [Pawsperity Biotechnologies](https://pawsperitybio.ca/), \
an early stage start-up working on improving animal health through biomarker discovery.  


In my free time I love to explore Vancouver's trails, practice yoga, and take pictures of \
flowers [@bloomvancouver](https://www.instagram.com/bloomvancouver/)).  I hope to share projects on a range of topics including just-for-fun \
data analyses, easy-to-follow tutorials, and more complex machine learning explorations.

'''
  alertbar = false

[params.social]
  github = "ursulahneumann"
  linkedin = "ursulahneumann"
  twitter = "ursulahneumann"
  instagram = "ursulahneumann"
  scholar = "dby1GCwAAAAJ"
  # xing = "<username>"
  # medium = "<username>"

## Main Menu
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 100
    url = "/"
[[menu.main]]
    name = "Blog"
    weight = 200
    identifier = "blog"
    url = "/blog"
#[[menu.main]]
#    name = "Imprint"
#    identifier = "imprint"
#    weight = 200
#    url = "/static/imprint"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'pygments'
    tabWidth = 4